### ISSUE TITLE
UI is breaking on few screens in Mobile device

### ISSUE THREAD

**Issue by vikramIde** [hypersign-protocol/whitelisting#29]
1.  Login Screen : Maybe some text size correction
2. Stepper 1 : the check boxes breaks to new line in andorid nokia phone 
3. Stepper 3 : The heading text is overlapping the form

**Comment by Vishwas1** [comment]
![image](https://user-images.githubusercontent.com/15328561/119651071-35859d00-be42-11eb-9a90-6b1db2f31b66.png)
